
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: satori
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.21.0"
              message: This application requires at least Kubernetes 1.21 or later, and recommends 1.24.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.24.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.24 or later.
              uri: https://kubernetes.io
          - pass:
              when: "=> 1.24.0"
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - storageClass:
        checkName: Check for default storage class
        outcomes:
          - fail:
              message: No default storage class found
          - pass:
              message: Default storage class found
    - distribution:
        outcomes:
          - pass:
              when: "== eks"
              message: EKS is a supported distribution
          - pass:
              when: "== gke"
              message: GKE is a supported distribution
          - pass:
              when: "== aks"
              message: AKS is a supported distribution
          - pass:
              when: "== rke2"
              message: RKE2 is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - nodeResources:
        checkName: Must have at least 3 nodes in the cluster
        outcomes:
        - fail:
            when: "count() < 3"
            message: This application requires at least 3 nodes.
        - pass:
            message: This cluster has enough nodes.
    - nodeResources:
        checkName: Every node in the cluster must have at least 7 GB of aloocatable memory
        outcomes:
        - fail:
            when: "min(memoryAllocatable) < 6.5Gi"
            message: All nodes must have at least 7 GB of aloocatable memory.
        - pass:
            message: All nodes have at least 7 GB of aloocatable memory.
    - nodeResources:
        checkName: Total CPU Cores in the cluster is 2 or greater
        outcomes:
          - fail:
              when: "sum(cpuCapacity) < 2"
              message: The cluster must contain at least 2 cores
          - pass:
              message: There are at least 2 cores in the cluster
    - nodeResources:
        checkName: Every node in the cluster must have at least 10 GB of ephemeral storage, with 100 GB recommended
        outcomes:
        - fail:
            when: "min(ephemeralStorageCapacity) < 10Gi"
            message: All nodes must have at least 10 GB of ephemeral storage.
        - warn:
            when: "min(ephemeralStorageCapacity) < 20Gi"
            message: All nodes are recommended to have at least 20 GB of ephemeral storage.
        - pass:
            message: All nodes have at least 10 GB of ephemeral storage.

